name: Release

on:
  push:
    tags:
    - 'v[0-9]+.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: curl -L https://unpkg.com/@pnpm/self-installer | node
      - run: |
          pnpm i --frozen-lockfile --no-verify-store-integrity
          pnpx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
